language: go
go:
  - "1.10.8"

env:
  - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=amd64 engine=docker"
  - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=amd64 engine=simple"
  - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=386   engine=simple"
  - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=arm   engine=simple"
  - "CGO_ENABLED=0 GIMME_OS=darwin  GIMME_ARCH=amd64 engine=simple"
  - "CGO_ENABLED=0 GIMME_OS=darwin  GIMME_ARCH=amd64 engine=multiuser"
  - "CGO_ENABLED=0 GIMME_OS=windows GIMME_ARCH=amd64 engine=multiuser"
  - "CGO_ENABLED=0 GIMME_OS=windows GIMME_ARCH=386   engine=multiuser"
  - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=amd64 engine=multiuser"

  # Currently broken:
  # - "CGO_ENABLED=0 GIMME_OS=linux   GIMME_ARCH=arm64 engine=simple"

install:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go get github.com/mattn/goveralls github.com/taskcluster/taskcluster-proxy github.com/taskcluster/livelog github.com/gordonklaus/ineffassign"

script:
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go get ./gw-codegen"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || go generate"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || git status"
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || test $(git status --porcelain | wc -l) == 0"
  - 'test $GIMME_OS.$GIMME_ARCH.$engine != linux.amd64.simple || test -z "${TASKCLUSTER_ACCESS_TOKEN}" || GORACE=history_size=7 travis_wait 60 ./gotestcover.sh $engine coverage.report'
  - 'test $GIMME_OS.$GIMME_ARCH.$engine != linux.amd64.simple || test -n "${TASKCLUSTER_ACCESS_TOKEN}" || CGO_ENABLED=1 GW_SKIP_INTEGRATION_TESTS=true GORACE=history_size=7 go test -tags "${engine}" -ldflags "-X github.com/taskcluster/generic-worker.revision=$(git rev-parse HEAD)" -v -race -timeout 1m'
  - 'go install -tags "${engine}" -ldflags "-X main.revision=$(git rev-parse HEAD)" -v ./...'
  - "test $GIMME_OS.$GIMME_ARCH != linux.amd64 || ${GOPATH}/bin/ineffassign ."

after_script:
  - "test '!' -f coverage.report || ${GOPATH}/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

before_deploy:
  - "source .travis_rename_releases.sh"

deploy:
  api_key:
    secure: KuifEWzfB5C9GFHMjFpSpbHWLN9cs/1afRuJhP4aADU3i55zb0QDzIu6+aGLlL0jsV5T07AqgPvJm4bOQNnWVhlhyHStrkIdzUpCtiCVNnPH3cYUkJ4/0zJyJaopnZfuX/2m2F+ajNC2Z94mxuu4qUUgqFO9x708xy0LYCofTEU=
  file:
    - "${RELEASE_FILE}"
  provider: releases
  skip_cleanup: true
  on:
    repo: taskcluster/generic-worker
    tags: true

notifications:
  irc:
    channels:
      - "irc.mozilla.org#taskcluster-bots"
    on_failure: always
    on_success: change
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
      - "Commit message : %{commit_message}"
