#!/bin/bash

set -exv
exec &> /var/log/userdata.log

# Version numbers ####################
GENERIC_WORKER_VERSION='v15.1.3'
LIVELOG_VERSION='v1.1.0'
TASKCLUSTER_PROXY_VERSION='v5.1.0'
######################################

function retry {
  set +e
  local n=0
  local max=10
  while true; do
    "$@" && break || {
      if [[ $n -lt $max ]]; then
        ((n++))
        echo "Command failed" >&2
        sleep_time=$((2 ** n))
        echo "Sleeping $sleep_time seconds..." >&2
        sleep $sleep_time
        echo "Attempt $n/$max:" >&2
      else
        echo "Failed after $n attempts." >&2
        exit 1
      fi
    }
  done
  set -e
}

start_time="$(date '+%s')"

retry apt update
retry apt upgrade -y
retry apt install -y apt-transport-https ca-certificates curl software-properties-common

# rootless docker deps
retry apt install -y uidmap slirp4netns

# install docker as unprivileged ubuntu user
# FIXME: curl | bash
retry curl -fsSL https://get.docker.com/rootless -o /home/ubuntu/get-docker.sh
su ubuntu -c 'cd $HOME && mkdir $HOME/bin && sh get-docker.sh'

# see: https://wiki.archlinux.org/index.php/Systemd/User
# start user docker service on boot as ubuntu
loginctl enable-linger ubuntu
sed -i 's/multi-user.target/default.target/' /home/ubuntu/.config/systemd/user/docker.service

# FIXME is this needed?
# su ubuntu -c 'systemctl --user enable docker'

# ensure docker in path, configure non-default docker socket
echo 'export PATH=/home/ubuntu/bin:$PATH
export DOCKER_HOST=unix:///run/user/1000/docker.sock' > /home/ubuntu/.bashrc


# install generic-worker into /home/ubuntu/generic-worker
mkdir -p /home/ubuntu/generic-worker
cd /home/ubuntu/generic-worker
retry curl -L "https://github.com/taskcluster/generic-worker/releases/download/${GENERIC_WORKER_VERSION}/generic-worker-simple-linux-amd64" > generic-worker
retry curl -L "https://github.com/taskcluster/livelog/releases/download/${LIVELOG_VERSION}/livelog-linux-amd64" > livelog
retry curl -L "https://github.com/taskcluster/taskcluster-proxy/releases/download/${TASKCLUSTER_PROXY_VERSION}/taskcluster-proxy-linux-amd64" > taskcluster-proxy
chmod a+x generic-worker taskcluster-proxy livelog
chown -R ubuntu:ubuntu /home/ubuntu/generic-worker
./generic-worker --version
./generic-worker new-ed25519-keypair --file ed25519.key

# ensure host 'taskcluster' resolves to localhost
echo 127.0.1.1 taskcluster >> /etc/hosts

# configure generic-worker to run on boot
echo '@reboot PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /home/ubuntu/generic-worker/generic-worker run --configure-for-aws --config /home/ubuntu/generic-worker/generic-worker.config >> /home/ubuntu/generic-worker/generic-worker.log 2>&1' | crontab -u ubuntu -

end_time="$(date '+%s')"
echo "UserData execution took: $(($end_time-$start_time)) seconds"

# shutdown so that instance can be snapshotted
shutdown now
